// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgdzxseqxhjtqzjxpbcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nZHp4c2VxeGhqdHF6anhwYmNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2Mjc5OTEsImV4cCI6MjA2OTIwMzk5MX0.z066cNKf3Gd9N_BLSxp8LrHcznO-M1tijZDDPhkRBzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});